[book]
title = "Julian Siebert"
authors = ["Julian Siebert"]
language = "en"

[output.html]
git-repository-url = "https://github.com/julian-siebert/julian-siebert"
edit-url-template = "https://github.com/julian-siebert/julian-siebert/edit/main/docs/{path}"
site-url = "/books/"
